{
 "title": "Flink Metrics With Custom KPI Metrics",
 "description": "Flink Metrics (with Kafka) on K8S\nThis dashboard if for monitoring Flink Applications Performance. It includes metrics like record count, latency. It also has kafka parameters like bytes count. Moreover, it has k8s memory, CPU and Network statistics.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Flink_Job_Name",
    "query": "label_values(flink_taskmanager_job_task_numRecordsOut,job_name)"
   },
   {
    "name": "Source",
    "query": "label_values(flink_taskmanager_job_task_numRecordsIn,task_name)"
   },
   {
    "name": "Sink",
    "query": "label_values(flink_taskmanager_job_task_numRecordsIn,task_name)"
   },
   {
    "name": "TaskManager",
    "query": "label_values(flink_taskmanager_Status_JVM_CPU_Load, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Job Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "numRecordsInPerSecond for Operator",
   "type": "graph",
   "description": "numRecordsInPerSecond for Operator",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Number of Records per second" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsInPerSecond{job_name=~\"$Flink_Job_Name\",task_name=~\"$Source\"}) by (task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "numRecordsOutPerSecond for Operator",
   "type": "graph",
   "description": "numRecordsOutPerSecond for Operator",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Number of Records per second" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job_name=~\"$Flink_Job_Name\",task_name=~\"$Source\"} )   by (task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "FlinkKafkaConsumer Latency",
   "type": "graph",
   "description": "Latency between EventTime and time when Flink got message",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "Latency in ms" }
   ],
   "targets": [
    {
     "expr": "max(flink_taskmanager_job_task_operator_kinesisanalytics_consumedByFlinkLatencyHistogram{job_name=~\"$Flink_Job_Name\",operator_name=~\"$Source\",quantile=\"0.99\"}) by (operator_name)",
     "legendFormat": "{{operator_name}}-max"
    },
    {
     "expr": "min(flink_taskmanager_job_task_operator_kinesisanalytics_consumedByFlinkLatencyHistogram{job_name=~\"$Flink_Job_Name\",operator_name=~\"$Source\",quantile=\"0.99\"}) by (operator_name)",
     "legendFormat": "{{operator_name}}-min"
    },
    {
     "expr": "avg(flink_taskmanager_job_task_operator_kinesisanalytics_consumedByFlinkLatencyHistogram{job_name=~\"$Flink_Job_Name\",operator_name=~\"$Source\",quantile=\"0.99\"}) by (operator_name)",
     "legendFormat": "{{operator_name}}-avg"
    }
   ]
  },
  {
   "title": "End2End Latency-SmoothingRequest",
   "type": "graph",
   "description": "End2End Latency-SmoothingRequest",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "Latency in ms" }
   ],
   "targets": [
    {
     "expr": "max(flink_taskmanager_job_task_operator_user_kinesisanalytics_e2eLatencyHistogram{operator_name=\"smoothing_request_sink:_Writer\",quantile=\"0.99\"}) by (operator_name)",
     "legendFormat": "{{operator_name}}"
    },
    {
     "expr": "min(flink_taskmanager_job_task_operator_user_kinesisanalytics_e2eLatencyHistogram{operator_name=\"smoothing_request_sink:_Writer\",quantile=\"0.99\"}) by (operator_name)",
     "legendFormat": "{{operator_name}}"
    },
    {
     "expr": "avg(flink_taskmanager_job_task_operator_user_kinesisanalytics_e2eLatencyHistogram{operator_name=\"smoothing_request_sink:_Writer\",quantile=\"0.99\"}) by (operator_name)",
     "legendFormat": "{{operator_name}}"
    }
   ]
  },
  {
   "title": "JdbcBatch latency",
   "type": "graph",
   "description": "Time which need to Sink data to DB",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none", "label": "Latency in ms" }
   ],
   "targets": [
    {
     "expr": "max(flink_taskmanager_job_task_operator_kinesisanalytics_batch_latencyHistogram{operator_name=\"rates_jdbc_sink:_Writer\",quantile=\"0.99\"}) by (operator_name)",
     "legendFormat": " {{operator_name}}-max"
    },
    {
     "expr": "min(flink_taskmanager_job_task_operator_kinesisanalytics_batch_latencyHistogram{operator_name=\"rates_jdbc_sink:_Writer\",quantile=\"0.99\"}) by (operator_name)",
     "legendFormat": " {{operator_name}}-min"
    },
    {
     "expr": "avg(flink_taskmanager_job_task_operator_kinesisanalytics_batch_latencyHistogram{operator_name=\"rates_jdbc_sink:_Writer\",quantile=\"0.99\"}) by (operator_name)",
     "legendFormat": " {{operator_name}}-avg"
    }
   ]
  },
  {
   "title": "JdbcBatch batch size",
   "type": "graph",
   "description": "Number of UPSERT commands (messages) in JDBC Statement",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "max(flink_taskmanager_job_task_operator_kinesisanalytics_batch_sizeHistogram{operator_name=\"rates_jdbc_sink:_Writer\",quantile=\"0.99\"}) by (operator_name)",
     "legendFormat": " {{operator_name}}-max"
    },
    {
     "expr": "min(flink_taskmanager_job_task_operator_kinesisanalytics_batch_sizeHistogram{operator_name=\"rates_jdbc_sink:_Writer\",quantile=\"0.99\"}) by (operator_name)",
     "legendFormat": " {{operator_name}}-min"
    },
    {
     "expr": "avg(flink_taskmanager_job_task_operator_kinesisanalytics_batch_sizeHistogram{operator_name=\"rates_jdbc_sink:_Writer\",quantile=\"0.99\"}) by (operator_name)",
     "legendFormat": " {{operator_name}}-avg"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Records" }
   ],
   "targets": [
    {
     "expr": "max(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_lag_max{job_name=~\"$Flink_Job_Name\"}) by (operator_name)",
     "legendFormat": "Max Lag/Consumer - {{operator_name}} "
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_lag_max{job_name=~\"$Flink_Job_Name\"}) by (job_name)",
     "legendFormat": "Total Consumer Lag - {{topic}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Input Queue Length",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none", "label": "Records" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_buffers_inputQueueLength{job_name=~\"$Flink_Job_Name\"}) by (task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Output Queue Length",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "Records" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_buffers_outputQueueLength{job_name=~\"$Flink_Job_Name\"}) by (task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  { "title": "Memory & CPU (TaskManager)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "TaskManager Heap Memory",
   "type": "graph",
   "description": "JVM Memory Heap Used vs JVM Memory Heap Max",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used{pod=~\"$TaskManager\"}",
     "legendFormat": "Heap Used {{pod}}"
    },
    {
     "expr": "avg(flink_taskmanager_Status_JVM_Memory_Heap_Committed{pod=~\"$TaskManager\"})",
     "legendFormat": "Heap Committed/pod"
    }
   ]
  },
  {
   "title": "TaskManager NonHeap Memory",
   "type": "graph",
   "description": "JVM Memory Heap Used vs JVM Memory Heap Max",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 46 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Used{pod=~\"$TaskManager\"}",
     "legendFormat": "NonHeap Used {{pod}}"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Max{pod=~\"$TaskManager\"}",
     "legendFormat": "NonHeap Max {{pod}}"
    }
   ]
  },
  {
   "title": "TaskManager Direct Memory",
   "type": "graph",
   "description": "JVM Memory Heap Used vs JVM Memory Heap Max",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed{pod=~\"$TaskManager\"}",
     "legendFormat": "Direct Used {{pod}}"
    }
   ]
  },
  {
   "title": "TaskManager Mapped Memory",
   "type": "graph",
   "description": "JVM Memory Heap Used vs JVM Memory Heap Max",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 55 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Mapped_MemoryUsed{pod=~\"$TaskManager\"}",
     "legendFormat": "Mapped Used {{pod}}"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Mapped_TotalCapacity{pod=~\"$TaskManager\"}",
     "legendFormat": "Mapped TotalCapacity {{pod}}"
    }
   ]
  },
  {
   "title": "CPU LOAD",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(100 * flink_jobmanager_Status_JVM_CPU_Load)",
     "legendFormat": "JobManagers"
    },
    {
     "expr": "100 * flink_taskmanager_Status_JVM_CPU_Load{pod=~\"$TaskManager\"}",
     "legendFormat": "TaskManager {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Load - TaskManager (24h)",
   "type": "singlestat",
   "description": "It's the rate over last 2 minutes.",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 64 },
   "format": "rps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(flink_taskmanager_Status_JVM_CPU_Load[2m]))"
    }
   ]
  },
  {
   "title": "CPU Load - JobManager (24h)",
   "type": "singlestat",
   "description": "It's the rate over last 2 minutes.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 64 },
   "format": "rps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(flink_jobmanager_Status_JVM_CPU_Load[2m]))"
    }
   ]
  },
  {
   "title": "Task Manager Garbage collection (time)",
   "type": "graph",
   "description": "Shows the amount of time spent performing garbage collection on each of the task managers",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time{pod=~\"$TaskManager\"}[10s])",
     "legendFormat": "G1 Old Time ({{pod}})"
    },
    {
     "expr": "rate(flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time{pod=~\"$TaskManager\"}[10s])",
     "legendFormat": "G1 Young Time ({{pod}})"
    }
   ]
  },
  {
   "title": "Task Manager Garbage collection (count)",
   "type": "graph",
   "description": "Shows the amount of time spent performing garbage collection on each of the task managers",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Count{pod=~\"$TaskManager\"}[10s])",
     "legendFormat": "G1 Young Count ({{pod}})"
    },
    {
     "expr": "rate(flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Count{pod=~\"$TaskManager\"}[10s])",
     "legendFormat": "G1 Old Count ({{pod}})"
    }
   ]
  },
  {
   "title": "Taskmanager Buffers",
   "type": "graph",
   "description": "JVM Memory Direct Buffers vs JVM Memory Total Capacity of Direct Buffers",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Direct_Count{pod=~\"$TaskManager\"}",
     "legendFormat": "Used: {{pod}}"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Direct_TotalCapacity{pod=~\"$TaskManager\"}",
     "legendFormat": "Available: {{pod}}"
    }
   ]
  },
  { "title": "Memory (JobManager)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "JobManager Buffers",
   "type": "graph",
   "description": "JVM Memory Direct Buffers vs JVM Memory Total Capacity of Direct Buffers",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Direct_Count{}",
     "legendFormat": "Used: {{pod}}"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Direct_TotalCapacity{}",
     "legendFormat": "Available: {{pod}}"
    }
   ]
  },
  {
   "title": "JobManager Heap Memory (All pods)",
   "type": "graph",
   "description": "JVM Memory Heap Used vs JVM Memory Heap Max",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(flink_jobmanager_Status_JVM_Memory_Heap_Used)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(flink_jobmanager_Status_JVM_Memory_Heap_Max)",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Rocksdb",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "cur-size-active-mem-table",
     "type": "graph",
     "description": "Monitor the approximate size of the active memtable in bytes.\n",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(job_id,job_name,task_name,host) (flink_taskmanager_job_task_operator_interestRatesState_rocksdb_cur_size_active_mem_table{component=\"taskmanager\",endpoint=\"metrics\"})",
       "legendFormat": "{{ host }}: {{ job_name }} - {{ task_name }}"
      }
     ]
    },
    {
     "title": "cur-size-all-mem-tables",
     "type": "graph",
     "description": "Monitor the approximate size of the active and unflushed immutable memtables in bytes.\n",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(job_id,job_name,task_name,host) (flink_taskmanager_job_task_operator_interestRatesState_rocksdb_cur_size_all_mem_tables{component=\"taskmanager\",endpoint=\"metrics\"})",
       "legendFormat": "{{ host }}: {{ job_name }} - {{ task_name }}"
      }
     ]
    },
    {
     "title": "estimate-live-data-size",
     "type": "graph",
     "description": "Estimate of the amount of live data in bytes.\n",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(job_id,job_name,task_name,host) (flink_taskmanager_job_task_operator_interestRatesState_rocksdb_estimate_live_data_size{component=\"taskmanager\",endpoint=\"metrics\"})",
       "legendFormat": "{{ host }}: {{ job_name }} - {{ task_name }}"
      }
     ]
    },
    {
     "title": "size-all-mem-tables",
     "type": "graph",
     "description": "Monitor the approximate size of the active, unflushed immutable, and pinned immutable memtables in bytes.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(job_id,job_name,task_name,host) (flink_taskmanager_job_task_operator_interestRatesState_rocksdb_size_all_mem_tables{component=\"taskmanager\",endpoint=\"metrics\"})",
       "legendFormat": "{{ host }}: {{ job_name }} - {{ task_name }}"
      }
     ]
    },
    {
     "title": "estimate-num-keys",
     "type": "graph",
     "description": "Estimate the number of keys in RocksDB.\n",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by(job_id,job_name,task_name,host) (flink_taskmanager_job_task_operator_interestRatesState_rocksdb_estimate_num_keys{component=\"taskmanager\",endpoint=\"metrics\"})",
       "legendFormat": "{{ host }}: {{ job_name }} - {{ task_name }}"
      }
     ]
    }
   ]
  },
  { "title": "Checkpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Last Checkpoint Duration",
   "type": "graph",
   "description": "The time it took to complete the last checkpoint (in milliseconds).\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (flink_jobmanager_job_lastCheckpointDuration{component=\"jobmanager\", endpoint=\"metrics\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Last Checkpoint Size",
   "type": "graph",
   "description": "The total size of the last checkpoint (in bytes).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (flink_jobmanager_job_lastCheckpointSize{component=\"jobmanager\", endpoint=\"metrics\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Last Checkpoint Restore Timestamp",
   "type": "singlestat",
   "description": "Timestamp when the last checkpoint was restored at the coordinator (in milliseconds).",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 110 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(flink_jobmanager_job_lastCheckpointRestoreTimestamp{component=\"jobmanager\", endpoint=\"metrics\"}) > 0"
    }
   ]
  },
  {
   "title": "Number Of Failed Checkpoints",
   "type": "graph",
   "description": "The number of failed checkpoints.",
   "gridPos": { "h": 9, "w": 17, "x": 6, "y": 110 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (flink_jobmanager_job_numberOfFailedCheckpoints{component=\"jobmanager\", endpoint=\"metrics\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Checkpoint Alignment Time",
   "type": "graph",
   "description": "The time in nanoseconds that the last barrier alignment took to complete, or how long the current alignment has taken so far (in nanoseconds).",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum by (job_id,task_name) (flink_taskmanager_job_task_checkpointAlignmentTime{component=\"taskmanager\", endpoint=\"metrics\"})",
     "legendFormat": "{{ task_name }}"
    }
   ]
  }
 ]
}